# Generated by Django 4.0 on 2022-09-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nft_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonefungibletoken',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nft_generator.account'),
        ),
        migrations.AlterField(
            model_name='nonefungibletoken',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nft_generator.token'),
        ),
    ]
